version: '3.3'

services:
  frontend: 
    container_name: frontend
    build: 
      context: ../teplo/
      dockerfile: Dockerfile
    
    ports: 
      - 3000:3000
    restart: always


  backend: 
    container_name: backend
    build: 
      context: .
    env_file:
      - .development.env
    volumes: 
      - .:/app
      - /app/node_modules
    ports: 
      - 3001:3001
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  
  
volumes:
  pgdata:
