version: '3.3'

services:
  frontend: 
    container_name: frontend
    env_file:
      - .production.env
    build: 
      context: ../teplo
      dockerfile: Dockerfile.production
    ports: 
      - 80:80
    depends_on:
      - backend
    restart: always
    
  backend: 
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile.production
    env_file:
      - .production.env
    ports: 
      - 3001:3001
    command: npm run start
    depends_on:
      - postgres
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  
  
volumes:
  pgdata:
